name: Docker CI

on: [push]

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install scikit-learn joblib

    - name: Run training
      run: python train.py

    - name: Build Docker image
      run: docker build -t vineeth4275/mlops-assignment3 .

    - name: Run container
      run: docker run your_dockerhub_username/mlops-assignment3

    - name: DockerHub Login & Push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push your_dockerhub_username/mlops-assignment3

